name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    name: Rust
    uses: so1ve/workflows/.github/workflows/rust-ci.yml@v1
    with:
      toolchain: nightly
      runs-on: ubuntu-24.04
      runs-on-matrix: '"ubuntu-24.04"'

  nix:
    name: Nix
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix fmt -- --ci
      - run: nix flake check --all-systems

  build:
    name: Build ${{ matrix.system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-24.04
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: so1ve
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}
      - run: nix build ".#packages.${{ matrix.system }}.default" --print-build-logs
